### ISSUE TITLE
Failing on object which is null

### ISSUE THREAD

**Issue by ycadaner-merkos302** [rodolfoviolac/blur-sensitive-data#20]
Hi,
https://gitkraken.dev/link/dnNjb2RlOi8vZWFtb2Rpby5naXRsZW5zL2xpbmsvci8zNTdlNThmYjQ3OTIxOTM0YmE3YWYxYzNmZjdmNzc1MTU5MDhhZTE2L2Yvbm9kZV9tb2R1bGVzL2JsdXItc2Vuc2l0aXZlLWRhdGEvZGlzdC9janMvdXRpbHMvb2JqZWN0SGFuZGxlci5qcz91cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIuY29tJTJGbWVya29zLTMwMiUyRm1lcmtvcy1wbGF0Zm9ybS5naXQ%3D?origin=gitlens
Seems this line needs a patch to account for null values.
```
 if (typeof objectToReplace[key] === 'object') {
            objectReplacer(objectToReplace[key], lookFor, stringReplacer);
        }
```
Should add 
```
 if (typeof objectToReplace[key] === 'object' &&  objectToReplace[key]  !== null) {
            objectReplacer(objectToReplace[key], lookFor, stringReplacer);
        }
```

**Comment by rodolfoviolac** [comment]
@ycadaner-merkos302 that is a good point! Thanks for sharing, I will make a fix for invalid payload data to prevent that kind of errors!

**Comment by rodolfoviolac** [comment]
@ycadaner-merkos302 just made a new release v.1.2.0 with MR #22! That shoud solve this problem
